source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'JPImageresizerView_Example' do
  pod 'JPImageresizerView', :path => '../'

  pod 'JPLiquidLayout'
  pod 'JPBasic/JPConst'
  pod 'JPBasic/JPCategory'
  pod 'JPBasic/JPProgressHUD'
  pod 'JPBasic/JPBrowseImages'
end
